/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controladores.ClienteController;
import java.io.IOException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.MonthDay;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Administrador;
import modelo.AgendaRestaurante;
import modelo.BloqueoMesaEventoEspecial;
import modelo.Cliente;
import modelo.CreadorPdf;
import modelo.CrearExcel;
import modelo.Empleado;
import modelo.Rol;
import modelo.Reserva;
import persistencia.ClasesDao.ClienteDAO;
import persistencia.ClasesDao.EmpleadoDAO;
import persistencia.ClasesDao.ReservaDAO;

/**
 * Jframe AdView al cual solo acceden los usuarios que son Administradores.
 * Dentro de esta interfaz grafica el usuario puede visualizar todas las
 * reservas, o filtarlas segun diferentes criterios. observar todos los cliente
 * y filtrarlos por su no asistencia o ver el mejor cliente. Observar todas las
 * mesas y realizar modificaciones en ellas como agreagar, eliminar, quitar
 * sillas,cambiar mesas de lugar o eliminar una mesa. Puede realizar el bloqueo
 * de mesas cuando estas son requeridas para un evento especial Puede visualizar
 * un analisis durante un periodo de tiempo. El administrador puede visualizar,
 * agregar o eliminar empleados.
 *
 * @author Marcos Ramon Caraballo, Angelina María Vialle,Valentin Rebechi,Ian
 * Caraballo
 * @version 27/10/2024
 */
public class AdView extends javax.swing.JFrame {

    private DefaultTableModel tabla;
    private Administrador administrador;
    private EmpleadoDAO empleadoDAO = new EmpleadoDAO();
    private ClienteDAO clienteDAO = new ClienteDAO();
    private Cliente cliente = new Cliente();
    private ReservaDAO reservaDAO = new ReservaDAO();
    ArrayList<BloqueoMesaEventoEspecial> bmes = new ArrayList<BloqueoMesaEventoEspecial>();
    BloqueoMesaEventoEspecial bme;
    ArrayList<Reserva> reservas;
    ArrayList<Cliente> clientes;
    private LocalDate fechaInicial;
    private LocalDate fechaFinal;
    private String tituloReservas;
    private String tituloClientes;
    private AgendaRestaurante agendaR;

    /**
     * Creates new form AdView
     *
     */
    public AdView(Administrador administrador) {
        initComponents();
        setSize(800,
                500);
        setResizable(false);
        setTitle("Panel de administracion");
        setLocationRelativeTo(null);
        this.administrador = administrador;
        tabla = (DefaultTableModel) jTableReporteReservas.getModel();
        agendaR = empleadoDAO.obtenerHoraAperturaCierre();
        bmes = empleadoDAO.obtenerBloqueosMesasEventosEspeciales();
        agendaR.setFechasEspecial(bmes);
        mostrarHorarioAperturaCierre();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Administrador_salir = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton_administrador_empleado_agregar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_empleadosAdmin = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox_administrador_empleado_rol = new javax.swing.JComboBox<>();
        jTextField_administrador_empleado_nombre = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField_administrador_empleado_correo = new javax.swing.JTextField();
        jButtonVerEmpleados = new javax.swing.JButton();
        jTextField_administrador_empleado_contrasenia = new javax.swing.JPasswordField();
        jPanel12 = new javax.swing.JPanel();
        jPanel_eventosEspeciales = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_fechaEvento = new javax.swing.JTextField();
        jButton_bloqueoMesas = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_bloqueoMesas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxHoraInicio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxHoraFin = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMesas = new javax.swing.JComboBox<>();
        jButtonVerBloqueMesaEvento = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelHoraCierre = new javax.swing.JLabel();
        jLabelHoraApertura = new javax.swing.JLabel();
        jBAperturaCierreModificar = new javax.swing.JButton();
        jComboBoxHoraApertura = new javax.swing.JComboBox<>();
        jComboBoxHoraCierre = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_clientesAdmin = new javax.swing.JTable();
        jBTodosClientes = new javax.swing.JButton();
        jBMejorCliente = new javax.swing.JButton();
        jBClientesNoAsistieron1Año = new javax.swing.JButton();
        jButtonExportarClientes = new javax.swing.JButton();
        Excelcliente = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableReporteReservas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jBReservasFuturas = new javax.swing.JButton();
        jBTodasLasReservas = new javax.swing.JButton();
        jBReservasFecha = new javax.swing.JButton();
        jTxtFechaInicial = new javax.swing.JTextField();
        jTxtFechaFinal = new javax.swing.JTextField();
        jTxtCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jBReporteREservasPdf = new javax.swing.JButton();
        Excel = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jTextFieldVerano = new javax.swing.JTextField();
        jTextFieldOtoño = new javax.swing.JTextField();
        jTextFieldInvierno = new javax.swing.JTextField();
        jTextFieldPrimavera = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jBAnalisisTiempoVer = new javax.swing.JButton();
        jBAnalisisTiempoPdf = new javax.swing.JButton();
        EstacionesExcel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Delicias Gourmet");

        jButton_Administrador_salir.setText("Salir");
        jButton_Administrador_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Administrador_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 463, Short.MAX_VALUE)
                .addComponent(jButton_Administrador_salir)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton_Administrador_salir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 60));

        jTabbedPane2.setBackground(new java.awt.Color(0, 102, 102));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrador"));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jTabbedPane2ComponentMoved(evt);
            }
        });
        jTabbedPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane2KeyPressed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados"));

        jButton_administrador_empleado_agregar.setText("Agregar");
        jButton_administrador_empleado_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_administrador_empleado_agregarActionPerformed(evt);
            }
        });

        jLabel23.setText("Contraseña: ");

        jTable_empleadosAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Correo", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_empleadosAdmin);

        jLabel24.setText("Correo:");

        jLabel25.setText("Rol:");

        jComboBox_administrador_empleado_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Mesero", "Recepcionista" }));
        jComboBox_administrador_empleado_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_administrador_empleado_rolActionPerformed(evt);
            }
        });

        jTextField_administrador_empleado_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_administrador_empleado_nombreActionPerformed(evt);
            }
        });

        jLabel26.setText("Nombre:");

        jButtonVerEmpleados.setText("Ver");
        jButtonVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_administrador_empleado_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_administrador_empleado_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jTextField_administrador_empleado_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jTextField_administrador_empleado_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183))))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jButtonVerEmpleados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_administrador_empleado_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextField_administrador_empleado_contrasenia, jTextField_administrador_empleado_correo});

        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField_administrador_empleado_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jComboBox_administrador_empleado_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel23)
                    .addComponent(jTextField_administrador_empleado_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_administrador_empleado_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerEmpleados)
                    .addComponent(jButton_administrador_empleado_agregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel11Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextField_administrador_empleado_contrasenia, jTextField_administrador_empleado_correo});

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jTabbedPane2.addTab("Empleados", jPanel7);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_eventosEspeciales.setBackground(new java.awt.Color(0, 102, 102));
        jPanel_eventosEspeciales.setBorder(javax.swing.BorderFactory.createTitledBorder("Bloqueo / Eventos"));

        jLabel13.setText("Fecha:");

        jTextField_fechaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fechaEventoActionPerformed(evt);
            }
        });

        jButton_bloqueoMesas.setText("Bloquear");
        jButton_bloqueoMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bloqueoMesasActionPerformed(evt);
            }
        });

        jTable_bloqueoMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mesa", "Fecha", "Hora Inicio", "Hora Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable_bloqueoMesas);

        jLabel4.setText("Hora Inicio");

        jComboBoxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "18", "20", "22", "00" }));

        jLabel5.setText("Hora Fin");

        jComboBoxHoraFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "18", "20", "22" }));

        jLabel6.setText("Mesa");

        jComboBoxMesas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesasActionPerformed(evt);
            }
        });

        jButtonVerBloqueMesaEvento.setText("Ver");
        jButtonVerBloqueMesaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerBloqueMesaEventoActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_eventosEspecialesLayout = new javax.swing.GroupLayout(jPanel_eventosEspeciales);
        jPanel_eventosEspeciales.setLayout(jPanel_eventosEspecialesLayout);
        jPanel_eventosEspecialesLayout.setHorizontalGroup(
            jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_eventosEspecialesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_eventosEspecialesLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_eventosEspecialesLayout.createSequentialGroup()
                        .addGroup(jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_eventosEspecialesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonVerBloqueMesaEvento))
                            .addGroup(jPanel_eventosEspecialesLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_fechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                                .addComponent(jButton_bloqueoMesas)))
                        .addGap(83, 83, 83))))
            .addGroup(jPanel_eventosEspecialesLayout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addGap(83, 83, 83))
        );
        jPanel_eventosEspecialesLayout.setVerticalGroup(
            jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_eventosEspecialesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_fechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_bloqueoMesas)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerBloqueMesaEvento)
                    .addComponent(jBEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTextField_fechaEvento.getAccessibleContext().setAccessibleName("");

        jPanel12.add(jPanel_eventosEspeciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 390));
        jPanel_eventosEspeciales.getAccessibleContext().setAccessibleName("Bloqueo eventos");

        jTabbedPane2.addTab("Bloqueo / Eventos", jPanel12);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabelHoraCierre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelHoraCierre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoraCierre.setText("Hora de Cierre:");

        jLabelHoraApertura.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelHoraApertura.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoraApertura.setText("Hora de apertura:");

        jBAperturaCierreModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBAperturaCierreModificar.setText("Modificar");
        jBAperturaCierreModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAperturaCierreModificarActionPerformed(evt);
            }
        });

        jComboBoxHoraApertura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxHoraApertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "18", "20", "22", "00" }));

        jComboBoxHoraCierre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxHoraCierre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "18", "20", "22", "00" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHoraApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHoraCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBAperturaCierreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxHoraCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxHoraApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxHoraApertura, jComboBoxHoraCierre, jLabelHoraApertura});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHoraApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxHoraApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxHoraCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHoraCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAperturaCierreModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxHoraApertura, jComboBoxHoraCierre, jLabelHoraApertura, jLabelHoraCierre});

        jTabbedPane2.addTab("Apertura y Cierre", jPanel2);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfil Clientes"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));
        jPanel9.setForeground(new java.awt.Color(0, 0, 0));

        jTable_clientesAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Telefono", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_clientesAdmin);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 250));

        jBTodosClientes.setText("Todos los clientes");
        jBTodosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTodosClientesActionPerformed(evt);
            }
        });
        jPanel5.add(jBTodosClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jBMejorCliente.setText("Mejor Cliente");
        jBMejorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMejorClienteActionPerformed(evt);
            }
        });
        jPanel5.add(jBMejorCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jBClientesNoAsistieron1Año.setText("Clientes que no asistieron en el último año");
        jBClientesNoAsistieron1Año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClientesNoAsistieron1AñoActionPerformed(evt);
            }
        });
        jPanel5.add(jBClientesNoAsistieron1Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jButtonExportarClientes.setText("Exportar a PDF");
        jButtonExportarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarClientesActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonExportarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        Excelcliente.setText("ExportarExcel");
        Excelcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcelclienteActionPerformed(evt);
            }
        });
        jPanel5.add(Excelcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        jTabbedPane2.addTab("Reporte Clientes", jPanel5);

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        jTableReporteReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mesa", "Fecha", "Hora", "Ocupación", "Finalización", "Cliente", "Comensales"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableReporteReservas);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Correo");

        jBReservasFuturas.setText("Reservas Futuras");
        jBReservasFuturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReservasFuturasActionPerformed(evt);
            }
        });

        jBTodasLasReservas.setText("Todas las reservas ");
        jBTodasLasReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTodasLasReservasActionPerformed(evt);
            }
        });

        jBReservasFecha.setText("Reservas Fecha");
        jBReservasFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReservasFechaActionPerformed(evt);
            }
        });

        jTxtFechaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFechaInicialActionPerformed(evt);
            }
        });

        jTxtFechaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFechaFinalActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fechas");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Inicial");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Final");

        jBReporteREservasPdf.setText("Exportar a PDF");
        jBReporteREservasPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReporteREservasPdfActionPerformed(evt);
            }
        });

        Excel.setText("Exportar a Excel");
        Excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jBReporteREservasPdf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Excel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jBReservasFecha)
                            .addComponent(jTxtFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(588, 588, 588)
                        .addComponent(jLabel8))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBTodasLasReservas)
                            .addComponent(jBReservasFuturas)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(589, 589, 589)
                        .addComponent(jLabel7))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTxtFechaFinal, jTxtFechaInicial});

        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBReservasFuturas)
                        .addGap(18, 18, 18)
                        .addComponent(jBTodasLasReservas)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBReservasFecha))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBReporteREservasPdf)
                            .addComponent(Excel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(52, 52, 52))
        );

        jTabbedPane2.addTab("Reporte Reservas", jPanel8);

        jPanel14.setBackground(new java.awt.Color(0, 102, 102));

        jTextFieldVerano.setEditable(false);
        jTextFieldVerano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVeranoActionPerformed(evt);
            }
        });

        jTextFieldOtoño.setEditable(false);

        jTextFieldInvierno.setEditable(false);

        jTextFieldPrimavera.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Verano");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Otoño");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Invierno");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel31.setText("Primavera");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel32.setText("Concurrencia por estacion");

        jBAnalisisTiempoVer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBAnalisisTiempoVer.setText("Ver");
        jBAnalisisTiempoVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnalisisTiempoVerActionPerformed(evt);
            }
        });

        jBAnalisisTiempoPdf.setText("Exportar a PDF");
        jBAnalisisTiempoPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnalisisTiempoPdfActionPerformed(evt);
            }
        });

        EstacionesExcel.setText("Exportar a Excel");
        EstacionesExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstacionesExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jBAnalisisTiempoVer)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPrimavera, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(29, 29, 29)
                                .addComponent(jTextFieldInvierno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(39, 39, 39)
                                .addComponent(jTextFieldOtoño, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(35, 35, 35)
                                .addComponent(jTextFieldVerano, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel32))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jBAnalisisTiempoPdf)
                        .addGap(56, 56, 56)
                        .addComponent(EstacionesExcel)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldVerano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOtoño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInvierno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrimavera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAnalisisTiempoVer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAnalisisTiempoPdf)
                    .addComponent(EstacionesExcel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBAnalisisTiempoPdf, jBAnalisisTiempoVer});

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Analisis Periodos Tiempo ", jPanel13);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 810, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * /**
     * el metodo actualizarTablaBloqueoEvento se encarga de generar una
     * actualizacion a la tabla que muestra los datos de los eventos cuando
     * surge alguna modificacion para que estos datos se muestren de forma
     * correcta
     */

    private void actualizarTablaBloqueoMesaEvento() {

        agendaR.setFechasEspecial(empleadoDAO.
                obtenerBloqueosMesasEventosEspeciales());

        DefaultTableModel model = (DefaultTableModel) jTable_bloqueoMesas.
                getModel();
        model.setRowCount(0); //Elimina las filas existentes;

        for (BloqueoMesaEventoEspecial b : agendaR.getFechasEspecial()) {
            String horaInicio;
            if (b.getHoraInicio() == null) {
                horaInicio = "";
            } else {
                horaInicio = b.getHoraInicio().format(DateTimeFormatter.
                        ofPattern("HH:mm:ss"));
            }
            String horaFin;
            if (b.getHoraFin() == null) {
                horaFin = "";
            } else {
                horaFin = b.getHoraFin().format(DateTimeFormatter.ofPattern(
                        "HH:mm:ss"));
            }
            model.addRow(new Object[]{
                b.getNumMesa() == 0 ? "Todas" : b.getNumMesa(),
                b.getFecha().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                horaInicio,
                horaFin
            });
        }

    }

    private void jButton_Administrador_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Administrador_salirActionPerformed
        dispose();
        Inicio login = new Inicio();
        login.setVisible(true);
    }//GEN-LAST:event_jButton_Administrador_salirActionPerformed
    /**
     * el metodo actualizarTablaMesas se encarga de generar una actualizacion a
     * la tabla que muestra los datos de las mesas cuando surge alguna
     * modificacion para que estos datos se muestren de forma correcta
     */
    private void actualizarTablaMesas() {

        ArrayList<Cliente> clientes = clienteDAO.obtenerClientes();

        DefaultTableModel model = (DefaultTableModel) this.jTable_clientesAdmin.
                getModel();
        model.setRowCount(0); // Limpia todas las filas existentes        

        for (Cliente c : clientes) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNombre(),
                c.getTelefono(),
                c.getCorreo()
            });
        }

    }

    /**
     * el metodo actualizarTablaCliente se encarga de generar una actualizacion
     * a la tabla que muestra los datos de los clientes cuando surge alguna
     * modificacion para que estos datos se muestren de forma correcta
     */
    private void actualizarTablaCliente(ArrayList<Cliente> clientes) {

        DefaultTableModel model = (DefaultTableModel) this.jTable_clientesAdmin.
                getModel();
        model.setRowCount(0); // Limpia todas las filas existentes        

        for (Cliente c : clientes) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNombre(),
                c.getTelefono(),
                c.getCorreo()
            });
        }

    }

    /**
     * el metodo actualizarTablaEmpleado se encarga de generar una actualizacion
     * a la tabla que muestra los datos de los empleados cuando surge alguna
     * modificacion para que estos datos se muestren de forma correcta
     */
    private void actualizarTablaEmpleado() {

        ArrayList<Empleado> empleados = empleadoDAO.obtenerEmpleados();

        DefaultTableModel model = (DefaultTableModel) this.jTable_empleadosAdmin.
                getModel();
        model.setRowCount(0); // Limpia todas las filas existentes        

        for (Empleado e : empleados) {
            model.addRow(new Object[]{
                e.getId(),
                e.getNombre(),
                e.getCorreo(),
                e.getRol().toString()
            });
        }
    }

    /**
     * el metodo actualizarTablaReservasCliente encarga de generar una
     * actualizacion a la tabla que muestra los datos de las reservas cuando
     * surge alguna modificacion para que estos datos se muestren de forma
     * correcta
     */
    private void actualizarTablaReservasCliente() {

        DefaultTableModel model = (DefaultTableModel) jTableReporteReservas.
                getModel();
        model.setRowCount(0); // Limpia todas las filas existentes        

        for (Reserva res : reservas) {
            String auxHoraInicio = "";
            String auxHoraFin = "";
            if (res.getTiempoOcupacion() != null) {
                auxHoraInicio = res.getTiempoOcupacion()
                        .format(DateTimeFormatter.ofPattern("HH:mm:ss"));
            }
            if (res.getTiempoFinalizacion() != null) {
                auxHoraFin = res.getTiempoFinalizacion()
                        .format(DateTimeFormatter.ofPattern("HH:mm:ss"));
            }
            model.addRow(new Object[]{
                res.getMesa().getNumero(),
                res.getFecha().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                res.getHora().format(DateTimeFormatter.ofPattern("HH:mm:ss")),
                auxHoraInicio,
                auxHoraFin,
                res.getCliente().getNombre(),
                res.getMesa().getCapacidad()
            });
        }

    }


    private void jTabbedPane2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2KeyPressed
    /**
     * Evento que se ejecuta cuando se aprieta el boton de eliminar en
     * bloqueo/eventos
     *
     * @param evt es evento de apretar el boton eliminar
     */
    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        bme = agendaR.getFechasEspecial().get(jTable_bloqueoMesas.
                getSelectedRow());
        /**
         * Se envia un mensaje al usuario, de confirmacion si el bloqueo se
         * elimina correctamente o de error en caso contrario
         */
        if (empleadoDAO.eliminarBloqueoEvento(bme)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Bloqueo o evento eliminado con éxito.",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            this.actualizarTablaBloqueoMesaEvento();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al eliminar bloqueo o evento",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBEliminarActionPerformed
    /**
     * Evento que se ejecuta cuando se aprieta el boton Se llama al metodo
     * actualizarTablaBloqueoMesaEvento
     *
     * @param evt es evento de apretar el boton actualizar
     */
    private void jButtonVerBloqueMesaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerBloqueMesaEventoActionPerformed
        actualizarTablaBloqueoMesaEvento();
    }//GEN-LAST:event_jButtonVerBloqueMesaEventoActionPerformed
    /**
     * Evento que se ejecuta cuando se aprieta el boton bloquear Se realiza el
     * bloqueo de la mesa si todo sale correctamente, de lo contrario si la
     * fecha ingresada no tiene el formato requerido, el horario de finalizacion
     * es mayor que el de inicio, se muestra un cartel de advertencia
     * solicitando corregir estos datos.
     *
     * @param evt es el evento de apretar el boton bloquear
     */
    private void jButton_bloqueoMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bloqueoMesasActionPerformed
        BloqueoMesaEventoEspecial b = new BloqueoMesaEventoEspecial();
        String auxFecha = jTextField_fechaEvento.getText();

        LocalDate fechaBloqueoEvento;
        if (ClienteController.esFormatoFechaValido(auxFecha)) {
            try {
                fechaBloqueoEvento = LocalDate.parse(auxFecha,
                        DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            } catch (java.time.format.DateTimeParseException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ingrese una fecha válida",
                        "Advertencia",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese una fecha en formato dd/mm/aaaa",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        b.setFecha(fechaBloqueoEvento);

        String auxNumMesa = jComboBoxMesas.getSelectedItem().toString();

        String auxHoraInicio = jComboBoxHoraInicio.getSelectedItem().toString();
        String auxHoraFin = jComboBoxHoraFin.getSelectedItem().toString();

        int numeroMesa;
        LocalTime horaInicio;
        LocalTime horaFin;
        if (auxNumMesa.equals("Todas")) {
            if (Integer.parseInt(auxHoraInicio)
                    >= Integer.parseInt(auxHoraFin)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "La hora de inicio del evento debe"
                        + " ser menor a la hora de su finalización",
                        "Advertencia",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            numeroMesa = 0;
            horaInicio = LocalTime.parse(auxHoraInicio + ":00:00",
                    DateTimeFormatter.ofPattern("HH:mm:ss"));
            horaFin = LocalTime.parse(auxHoraFin + ":00:00",
                    DateTimeFormatter.ofPattern("HH:mm:ss"));

            b.setNumMesa(numeroMesa);
            b.setHoraInicio(horaInicio);
            b.setHoraFin(horaFin);

            if (!empleadoDAO.existeBloqueoEvento(b)) {
                if (empleadoDAO.bloquearMesaEventoEspecial(b)) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Se añadió el evento.",
                            "Éxito",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Ocurrió un error al añadir el evento",
                            "Advertencia",
                            javax.swing.JOptionPane.WARNING_MESSAGE);
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "El evento o bloqueo ingresado ya está registrado",
                        "Advertencia",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
            }

        } else {
            numeroMesa = Integer.parseInt(auxNumMesa);
            b.setNumMesa(numeroMesa);
            System.out.println(b.getHoraInicio());
            if (!empleadoDAO.existeBloqueoEvento(b)) {
                if (empleadoDAO.bloquearMesaEventoEspecial(b)) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Se añadió el bloqueo de mesa.",
                            "Éxito",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Ocurrió un error al añadir el bloqueo de mesa",
                            "Advertencia",
                            javax.swing.JOptionPane.WARNING_MESSAGE);
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "El evento o bloqueo ingresado ya está registrado",
                        "Advertencia",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }
        actualizarTablaBloqueoMesaEvento();
    }//GEN-LAST:event_jButton_bloqueoMesasActionPerformed

    private void jTextField_fechaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fechaEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fechaEventoActionPerformed

    private void jTxtFechaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFechaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFechaFinalActionPerformed

    private void jTxtFechaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFechaInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFechaInicialActionPerformed
    /**
     * Es el evento que se produce al oprimir el boton ReservasFechas Se
     * verifica que la fecha ingresada sea del formato solicitado de lo
     * contrario se muestra una advertencia En el panel existen el filtro de
     * fecha inicial y final, se controla que la fecha final no sea menor a la
     * inicial Se muestran en la tabla todas las reservas realizadas dentro de
     * las fechas inicial y final
     *
     * @param evt es evento de apretar el boton ReservasFecha
     */
    private void jBReservasFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReservasFechaActionPerformed

        String auxFechaI = jTxtFechaInicial.getText();
        String auxFechaF = jTxtFechaFinal.getText();
        if (!ClienteController.esFormatoFechaValido(auxFechaI)
                | !ClienteController.esFormatoFechaValido(auxFechaF)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese fechas en formato dd/mm/aaaa",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            fechaInicial = LocalDate.parse(auxFechaI,
                    DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            fechaFinal = LocalDate.parse(auxFechaF,
                    DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } catch (java.time.format.DateTimeParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese fechas válidas",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (fechaInicial.isAfter(fechaFinal)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La fecha inicial no puede ser mayor a la fecha final",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            reservas = reservaDAO.obtenerReservas();

            for (int i = 0; i < reservas.size(); i++) {
                Reserva res = reservas.get(i);
                if (res.getFecha().isBefore(fechaInicial)
                        || res.getFecha().isAfter(fechaFinal)) {
                    reservas.remove(res);
                    i--;
                }
            }

            tituloReservas = "Reservas entre fechas";

            actualizarTablaReservasCliente();

        }


    }//GEN-LAST:event_jBReservasFechaActionPerformed
    /**
     * Es el evento que se produce al oprimir el boton Todas las Reservas. Como
     * resultado muestra en la tabla todas las reservas realizadas
     *
     * @param evt evento de presionar el boton Todas las Reservas
     *
     */
    private void jBTodasLasReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTodasLasReservasActionPerformed

        if (verificarCliente()) {
            reservas = reservaDAO.obtenerReservasHistorial(cliente);
            tituloReservas = "Todas las reservas de " + cliente.getNombre();
            actualizarTablaReservasCliente();
        }
    }//GEN-LAST:event_jBTodasLasReservasActionPerformed
    /**
     * el metodo verificarCliente se encarga de controlar si el cliente buscado
     * se encuentra dentro de nuestro registro
     *
     * @return true si el cliente se encuentra registrado, false si el cliente
     * no esta
     */
    private boolean verificarCliente() {
        if (jTxtCorreo.getText().equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese un cliente",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return false;
        }

        cliente = clienteDAO.obtenerCliente(jTxtCorreo.getText());

        if (!cliente.getCorreo().equals(jTxtCorreo.getText())) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "No existe un cliente con el correo ingresado",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     * Es el evento que se produce al oprimir el boton Reservas futuras. Como
     * resultado muestra en la tabla todas las reservas que se realizaron para
     * fechas futuras a la actual
     *
     * @param evt evento de presionar el boton Reservas Futuras
     */
    private void jBReservasFuturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReservasFuturasActionPerformed
        if (verificarCliente()) {
            reservas = reservaDAO.obtenerReservasHistorial(cliente);

            for (int i = 0; i < reservas.size(); i++) {
                Reserva res = reservas.get(i);
                if (LocalDateTime.of(res.getFecha(),
                        res.getHora())
                        .isBefore(LocalDateTime.now())) {
                    reservas.remove(res);
                    i--;
                }
            }
            tituloReservas = "Reservas Futuras de " + cliente.getNombre();
            actualizarTablaReservasCliente();
        }
    }//GEN-LAST:event_jBReservasFuturasActionPerformed
    /**
     * Se llama al metodo de actualizarTablaEmpleado al presionar el boton ver
     *
     * @param evt es el evento de presionar el boton ver
     */
    private void jButtonVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerEmpleadosActionPerformed
        actualizarTablaEmpleado();
    }//GEN-LAST:event_jButtonVerEmpleadosActionPerformed

    private void jTextField_administrador_empleado_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_administrador_empleado_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_administrador_empleado_nombreActionPerformed

    private void jComboBox_administrador_empleado_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_administrador_empleado_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_administrador_empleado_rolActionPerformed
    /**
     * es el evento que se produce al apretar el boton agregar. Aqui se verifica
     * que los datos ingresados para la creacion del nuevo usuario sean validos.
     * Si existe un error en alguno de ellos se mostraran distintas advertencias
     * por pantalla. Si el nuevo usuario es agregado correctamente se muestra
     * por pantalla una confirmacion.
     *
     * @param evt es el evento de presionar el boton agregar
     */
    private void jButton_administrador_empleado_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_administrador_empleado_agregarActionPerformed
        String nombre = this.jTextField_administrador_empleado_nombre.getText();
        String correo = this.jTextField_administrador_empleado_correo.getText();
        String contrasenia = String.valueOf(
                this.jTextField_administrador_empleado_contrasenia.getPassword());
        Rol rol = null;
        switch (this.jComboBox_administrador_empleado_rol.getSelectedItem().
                toString()) {
            case "Administrador":
                rol = Rol.Administrador;
                break;
            case "Mesero":
                rol = Rol.Mesero;
                break;
            case "Recepcionista":
                rol = Rol.Recepcionista;
                break;
            default:
                break;
        }
        if (nombre.equals("")
                || correo.equals("")
                || contrasenia.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Debe completar todos los campos",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            if (ClienteController.esCorreoElectronicoValido(correo)) {
                Empleado emp = new Empleado();
                emp.setNombre(nombre);
                emp.setCorreo(correo);
                emp.setContrasenia(contrasenia);
                emp.setRol(rol);
                System.out.println(emp);
                if (empleadoDAO.registrarEmpleado(emp)) {
                    javax.swing.JOptionPane.showMessageDialog(null,
                            "Registrado exitosamente");
                    actualizarTablaEmpleado();
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(null,
                        "Ingrese un correo electronico valido",
                        "Advertencia",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButton_administrador_empleado_agregarActionPerformed
    /**
     * Metodo que se aplica al apretaron el boton Se obtiene el listado de los
     * clientes
     *
     * @param evt es el evento de apretar el boton
     */
    private void jBTodosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTodosClientesActionPerformed
        clientes = clienteDAO.obtenerClientes();
        this.tituloClientes = "Lista de clientes";
        actualizarTablaCliente(clientes);
    }//GEN-LAST:event_jBTodosClientesActionPerformed

    private void jTextFieldVeranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVeranoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVeranoActionPerformed
    /**
     *
     * @param evt
     */
    private void jBMejorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMejorClienteActionPerformed
        clientes = clienteDAO.obtenerClientes();
        int maxAsistencias = 0;
        for (int i = 0; i < clientes.size(); i++) {
            Cliente auxCliente = clientes.get(i);
            int auxAsistencia = reservaDAO.cantidadAsistencias(auxCliente);
            if (auxAsistencia < maxAsistencias) {
                clientes.remove(i);
                i--;
            } else if (auxAsistencia > maxAsistencias) {
                maxAsistencias = auxAsistencia;
                i = -1;
            }
        }
        this.tituloClientes = "Cliente(s) con mayor cantidad asistencias";
        actualizarTablaCliente(clientes);
    }//GEN-LAST:event_jBMejorClienteActionPerformed
    /**
     * Metodo que se aplica al apretar el boton Clientes que no asistieron el
     * ultimo año Muestra en la lista los clientes que no han asistido a sus
     * reservas en el ultimo año
     *
     * @param evt es el evento de presionar el boton
     */
    private void jBClientesNoAsistieron1AñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClientesNoAsistieron1AñoActionPerformed
        clientes = clienteDAO.obtenerClientes();
        for (Cliente cliente : clientes) {
            cliente.setReservas(reservaDAO.obtenerReservasHistorial(cliente));
        }

        int conti = 0;
        for (int i = 0; i < clientes.size(); i++) {
            System.out.println(conti++);

            Cliente auxCliente = clientes.get(i);
            ArrayList<Reserva> auxReservas = auxCliente.getReservas();
            if (auxReservas.isEmpty()) {
                clientes.remove(i);
                i--;
            } else {
                boolean inasistenciaEnAño = false;
                for (Reserva res : auxReservas) {
                    LocalDateTime auxF = LocalDateTime.of(res.getFecha(),
                            res.getHora());
                    System.out.println(auxF);
                    System.out.println(res.getCliente().getNombre());
                    System.out.println("" + res.getAsistencia());
                    if (auxF.isAfter(LocalDateTime.now().minusYears(1))
                            && auxF.isBefore(LocalDateTime.now())) {
                        if (!res.getAsistencia()) {
                            inasistenciaEnAño = true;
                            break;
                        }
                    }
                }
                if (!inasistenciaEnAño) {
                    clientes.remove(i);
                    i--;
                }
            }

        }
        this.tituloClientes = "Clientes que no asistieron en el último año";
        actualizarTablaCliente(clientes);
    }//GEN-LAST:event_jBClientesNoAsistieron1AñoActionPerformed
    /**
     * Es el metodo que se ejecuta al presionar el boton Ver Muestra la
     * concurrencia de clientes por estacion del año.
     *
     * @param evt es el evento de presionar el boton de Ver
     */
    private void jBAnalisisTiempoVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnalisisTiempoVerActionPerformed
        reservas = reservaDAO.obtenerReservas();

        MonthDay verano = MonthDay.of(12,
                20);
        MonthDay primavera = MonthDay.of(11,
                20);
        MonthDay invierno = MonthDay.of(6,
                20);
        MonthDay otoño = MonthDay.of(3,
                20);

        int cantVerano = 0;
        int cantPrimavera = 0;
        int cantInvierno = 0;
        int cantOtoño = 0;
        for (Reserva res : reservas) {
            if (res.getAsistencia()) {
                continue;
            }
            LocalDate aux = res.getFecha();
            MonthDay MesDiaR = MonthDay.of(aux.getMonth(),
                    aux.getDayOfMonth());
            if (MesDiaR.isAfter(verano)) {
                cantVerano++;
            } else if (MesDiaR.isAfter(primavera)) {
                cantPrimavera++;
            } else if (MesDiaR.isAfter(invierno)) {
                cantInvierno++;
            } else if (MesDiaR.isAfter(otoño)) {
                cantOtoño++;
            } else {
                cantVerano++;
            }
        }

        this.jTextFieldVerano.setText(String.valueOf(cantVerano));
        this.jTextFieldOtoño.setText(String.valueOf(cantOtoño));
        this.jTextFieldInvierno.setText(String.valueOf(cantInvierno));
        this.jTextFieldPrimavera.setText(String.valueOf(cantPrimavera));


    }//GEN-LAST:event_jBAnalisisTiempoVerActionPerformed
    /**
     * Es el metodo que se ejecuta al presionar el boton Exportar a PDF Se crea
     * y exporta un archivo pdf con la informacion que contiene la taba
     *
     * @param evt es el evento de presionar el boton Exportar a PDF
     */
    private void jBReporteREservasPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReporteREservasPdfActionPerformed
        if (reservas == null || reservas.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La tabla está vacía",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else if (tituloReservas.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe cargar nuevamente la tabla para volver a imprimir",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                CreadorPdf.hacerPdfReserva(tituloReservas,
                        reservas);
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Se exportó a pdf en la carpeta PDFsExportados",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBReporteREservasPdfActionPerformed

    private void jTabbedPane2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTabbedPane2ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2ComponentMoved
    /**
     * Metodo que se aplica al apretar el boton Exportar a PDF Se crea y exporta
     * un archivo PDf con la informacion que contiene la tabla
     *
     * @param evt es el evento de presionar el boton Exportar a PDF
     */
    private void jButtonExportarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarClientesActionPerformed

        if (clientes == null || clientes.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La tabla está vacía",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else if (tituloClientes.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe cargar la tabla para poder exportarla",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                CreadorPdf.hacerPdfCliente(tituloClientes,
                        clientes);
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Se exportó a pdf en la carpeta PDFsExportados",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExportarClientesActionPerformed
    /**
     * Metodo que muestra los horarios de apertura y cierre
     */
    private void mostrarHorarioAperturaCierre() {
        System.out.println(agendaR.getHoraApertura());
        System.out.println(agendaR.getHoraCierre());
        switch (agendaR.getHoraApertura().
                format(DateTimeFormatter.ofPattern("HH:mm:ss"))) {
            case "12:00:00":
                jComboBoxHoraApertura.setSelectedIndex(0);
                break;
            case "14:00:00":
                jComboBoxHoraApertura.setSelectedIndex(1);
                break;
            case "16:00:00":
                jComboBoxHoraApertura.setSelectedIndex(2);
                break;
            case "18:00:00":
                jComboBoxHoraApertura.setSelectedIndex(3);
                break;
            case "20:00:00":
                jComboBoxHoraApertura.setSelectedIndex(4);
                break;
            case "22:00:00":
                jComboBoxHoraApertura.setSelectedIndex(5);
                break;
            case "23:59:59":
                jComboBoxHoraApertura.setSelectedIndex(6);
                break;

        }
        switch (agendaR.getHoraCierre().
                format(DateTimeFormatter.ofPattern("HH:mm:ss"))) {
            case "12:00:00":
                jComboBoxHoraCierre.setSelectedIndex(0);
                break;
            case "14:00:00":
                jComboBoxHoraCierre.setSelectedIndex(1);
                break;
            case "16:00:00":
                jComboBoxHoraCierre.setSelectedIndex(2);
                break;
            case "18:00:00":
                jComboBoxHoraCierre.setSelectedIndex(3);
                break;
            case "20:00:00":
                jComboBoxHoraCierre.setSelectedIndex(4);
                break;
            case "22:00:00":
                jComboBoxHoraCierre.setSelectedIndex(5);
                break;
            case "23:59:59":
                jComboBoxHoraCierre.setSelectedIndex(6);
                break;

        }
    }

    /**
     * Metodo que se aplica al apretar el boton Modificar. Modifica el horario
     * de apertura y cierre del restaurante. verifica que los horarios
     * ingresados sean validos. Se controla que el horario de apertura sea menor
     * que el de cierre.
     *
     * @param evt
     */
    private void jBAperturaCierreModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAperturaCierreModificarActionPerformed
        String auxHoraAp = jComboBoxHoraApertura.
                getSelectedItem().toString() + ":00:00";
        String auxHoraCi = jComboBoxHoraCierre.
                getSelectedItem().toString() + ":00:00";
        if (auxHoraCi.equals("00:00:00")) {
            auxHoraCi = "23:59:59";
        }
        LocalTime horaAp = LocalTime.parse(auxHoraAp,
                DateTimeFormatter.ofPattern("HH:mm:ss"));
        LocalTime horaCi = LocalTime.parse(auxHoraCi,
                DateTimeFormatter.ofPattern("HH:mm:ss"));
        if (horaAp.isAfter(horaCi) || horaAp.equals(horaCi)) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La fecha inicial no puede ser mayor"
                    + " o igual a la fecha final",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {

            if (empleadoDAO.definirHoraAperturaCierre(horaAp,
                    horaCi)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Horario modificado con éxito",
                        "Advertencia",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                agendaR.setHoraApertura(horaAp);
                agendaR.setHoraCierre(horaCi);
                mostrarHorarioAperturaCierre();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Ocurrió un problema",
                        "Advertencia",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBAperturaCierreModificarActionPerformed
    /**
     * Es el Metodo que se ejecuta al cambiar la opciones del jComboBox
     *
     * @param evt es el evento de cambiar de opcion del JComboBox
     */
    private void jComboBoxMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesasActionPerformed
        // TODO add your handling code here:
        if (!jComboBoxMesas.getSelectedItem().toString().equals("Todas")) {
            jComboBoxHoraInicio.setSelectedIndex(0);
            jComboBoxHoraFin.setSelectedIndex(5);
            jComboBoxHoraInicio.setEnabled(false);
            jComboBoxHoraFin.setEnabled(false);
        } else {

            jComboBoxHoraInicio.setEnabled(true);
            jComboBoxHoraFin.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxMesasActionPerformed
    /**
     * Es el metodo que se aplica al presionar el boton Exportar a PDF Se
     * encarga de crear y exportar un archivo pdf con los datos mostrados de
     * concurrencia por estacion Verifica que existan datos.
     *
     * @param evt es el evento de presionar el boton Expotar a PDF
     */
    private void jBAnalisisTiempoPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnalisisTiempoPdfActionPerformed
        String verano = jTextFieldVerano.getText();
        String otoño = jTextFieldOtoño.getText();
        String invierno = jTextFieldInvierno.getText();
        String primavera = jTextFieldPrimavera.getText();
        if (verano.equals("")
                || otoño.equals("")
                || invierno.equals("")
                || primavera.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe cargar la tabla para poder exportarla",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                CreadorPdf.hacerPdfEstaciones("ConcurrenciasPorEstacion",
                        new String[]{verano, otoño, invierno, primavera});
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Se exportó a pdf en la carpeta PDFsExportados",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBAnalisisTiempoPdfActionPerformed
    /**
     * Metodo que exporta el listado de las reservas en un archivo excel
     *
     * @param evt es el evento de apretar el boton exportar a excel
     */
    private void ExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcelActionPerformed
        if (reservas == null || reservas.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La tabla está vacía",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else if (tituloReservas.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe cargar la tabla para poder exportarla",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                CrearExcel.hacerExcelReserva(tituloReservas,
                        reservas);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Se exportó a excel en la carpeta ExcelExportados",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_ExcelActionPerformed
    /**
     * Metodo que exporta el listado de clientes en un archivo excel
     *
     * @param evt es el evento de apretar el boton exportar a excel
     */
    private void ExcelclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcelclienteActionPerformed
        if (clientes == null || clientes.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "La tabla está vacía",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else if (tituloClientes.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe cargar la tabla para poder exportarla",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                CrearExcel.hacerExcelCliente(tituloClientes,
                        clientes);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Se exportó a excel en la carpeta ExcelExportados",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_ExcelclienteActionPerformed
    /**
     * Metodo que exporta el analisis de concurrencia por estacion en un archivo
     * excel
     *
     * @param evt es el evento de apretar el boton exportar a excel
     */
    private void EstacionesExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstacionesExcelActionPerformed
        String verano = jTextFieldVerano.getText();
        String otoño = jTextFieldOtoño.getText();
        String invierno = jTextFieldInvierno.getText();
        String primavera = jTextFieldPrimavera.getText();
        if (verano.equals("")
                || otoño.equals("")
                || invierno.equals("")
                || primavera.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Debe cargar la tabla para poder exportarla",
                    "Advertencia",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                CrearExcel.HacerExcelEstaciones(
                            new String[]{verano, otoño, invierno, primavera});
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Se exportó a pdf en la carpeta ExcelExportados",
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_EstacionesExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EstacionesExcel;
    private javax.swing.JButton Excel;
    private javax.swing.JButton Excelcliente;
    private javax.swing.JButton jBAnalisisTiempoPdf;
    private javax.swing.JButton jBAnalisisTiempoVer;
    private javax.swing.JButton jBAperturaCierreModificar;
    private javax.swing.JButton jBClientesNoAsistieron1Año;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBMejorCliente;
    private javax.swing.JButton jBReporteREservasPdf;
    private javax.swing.JButton jBReservasFecha;
    private javax.swing.JButton jBReservasFuturas;
    private javax.swing.JButton jBTodasLasReservas;
    private javax.swing.JButton jBTodosClientes;
    private javax.swing.JButton jButtonExportarClientes;
    private javax.swing.JButton jButtonVerBloqueMesaEvento;
    private javax.swing.JButton jButtonVerEmpleados;
    public javax.swing.JButton jButton_Administrador_salir;
    public javax.swing.JButton jButton_administrador_empleado_agregar;
    private javax.swing.JButton jButton_bloqueoMesas;
    private javax.swing.JComboBox<String> jComboBoxHoraApertura;
    private javax.swing.JComboBox<String> jComboBoxHoraCierre;
    private javax.swing.JComboBox<String> jComboBoxHoraFin;
    private javax.swing.JComboBox<String> jComboBoxHoraInicio;
    private javax.swing.JComboBox<String> jComboBoxMesas;
    public javax.swing.JComboBox<String> jComboBox_administrador_empleado_rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelHoraApertura;
    private javax.swing.JLabel jLabelHoraCierre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_eventosEspeciales;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableReporteReservas;
    public javax.swing.JTable jTable_bloqueoMesas;
    public javax.swing.JTable jTable_clientesAdmin;
    public javax.swing.JTable jTable_empleadosAdmin;
    private javax.swing.JTextField jTextFieldInvierno;
    private javax.swing.JTextField jTextFieldOtoño;
    private javax.swing.JTextField jTextFieldPrimavera;
    private javax.swing.JTextField jTextFieldVerano;
    private javax.swing.JPasswordField jTextField_administrador_empleado_contrasenia;
    public javax.swing.JTextField jTextField_administrador_empleado_correo;
    public javax.swing.JTextField jTextField_administrador_empleado_nombre;
    public javax.swing.JTextField jTextField_fechaEvento;
    private javax.swing.JTextField jTxtCorreo;
    private javax.swing.JTextField jTxtFechaFinal;
    private javax.swing.JTextField jTxtFechaInicial;
    // End of variables declaration//GEN-END:variables

}
