/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controladores.ClienteController;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Administrador;
import modelo.BloqueoMesaEventoEspecial;
import modelo.Cliente;
import modelo.Empleado;
import modelo.Rol;
import persistencia.ClasesDao.ClienteDAO;
import persistencia.ClasesDao.EmpleadoDAO;

/**
 *
 * @author Rebechi
 */
public class AdView extends javax.swing.JFrame {
    private DefaultTableModel tabla;
    private Administrador administrador;
    private EmpleadoDAO empleadoDAO = new EmpleadoDAO();
    private ClienteDAO clienteDAO = new ClienteDAO();
    ArrayList<BloqueoMesaEventoEspecial> bmes = new ArrayList<BloqueoMesaEventoEspecial>();
    BloqueoMesaEventoEspecial bme;
    
    /**
     * Creates new form AdView
     */
    public AdView(Administrador administrador) {
        initComponents();
        setSize(900, 500);
        setResizable(false);
        setTitle("Panel de administracion");
        setLocationRelativeTo(null);
        this.administrador = administrador;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_Administrador_salir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel_reservas = new javax.swing.JPanel();
        txt_reservas = new javax.swing.JLabel();
        jPanel_clientes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel_mesas = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel_empleados = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel_balances = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel_eventos = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_reservasAdmin = new javax.swing.JTable();
        jTextField_administrador_reserva_id = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextField_administrador_reserva_fecha = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField_administrador_reserva_cliente = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jButton_administrador_reservas_agregar = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_clientesAdmin = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_mesasAdmin = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jComboBox_administrador_mesas_ubi = new javax.swing.JComboBox<>();
        btn_administrador_mesa_modificar = new javax.swing.JButton();
        btn_administrador_mesa_eliminar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jTextField_administrador_mesa_cliente = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton_administrador_empleado_agregar = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_empleadosAdmin = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox_administrador_empleado_rol = new javax.swing.JComboBox<>();
        jTextField_administrador_empleado_nombre = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField_administrador_empleado_correo = new javax.swing.JTextField();
        jButtonVerEmpleados = new javax.swing.JButton();
        jTextField_administrador_empleado_contrasenia = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel_eventosEspeciales = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_fechaEvento = new javax.swing.JTextField();
        jButton_bloqueoMesas = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_bloqueoMesas = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxHoraInicio = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxHoraFin = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMesas = new javax.swing.JComboBox<>();
        jButtonVerBloqueMesaEvento = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Restaurante Floripa");

        jButton_Administrador_salir.setText("Salir");
        jButton_Administrador_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Administrador_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 428, Short.MAX_VALUE)
                .addComponent(jButton_Administrador_salir)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton_Administrador_salir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 810, 60));

        jLabel2.setText("Logo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 50));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_reservas.setBackground(new java.awt.Color(0, 102, 102));
        jPanel_reservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_reservasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_reservasMouseExited(evt);
            }
        });

        txt_reservas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_reservas.setText("Reservas");
        txt_reservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_reservasMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel_reservasLayout = new javax.swing.GroupLayout(jPanel_reservas);
        jPanel_reservas.setLayout(jPanel_reservasLayout);
        jPanel_reservasLayout.setHorizontalGroup(
            jPanel_reservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_reservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_reservas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel_reservasLayout.setVerticalGroup(
            jPanel_reservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_reservasLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(txt_reservas))
        );

        jPanel3.add(jPanel_reservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 30));

        jPanel_clientes.setBackground(new java.awt.Color(0, 102, 102));
        jPanel_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_clientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_clientesMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Clientes");

        javax.swing.GroupLayout jPanel_clientesLayout = new javax.swing.GroupLayout(jPanel_clientes);
        jPanel_clientes.setLayout(jPanel_clientesLayout);
        jPanel_clientesLayout.setHorizontalGroup(
            jPanel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel_clientesLayout.setVerticalGroup(
            jPanel_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 90, 30));

        jPanel_mesas.setBackground(new java.awt.Color(0, 102, 102));
        jPanel_mesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_mesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_mesasMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Mesas");

        javax.swing.GroupLayout jPanel_mesasLayout = new javax.swing.GroupLayout(jPanel_mesas);
        jPanel_mesas.setLayout(jPanel_mesasLayout);
        jPanel_mesasLayout.setHorizontalGroup(
            jPanel_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel_mesasLayout.setVerticalGroup(
            jPanel_mesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel_mesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 90, 30));

        jPanel_empleados.setBackground(new java.awt.Color(0, 102, 102));
        jPanel_empleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_empleadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_empleadosMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Empleados");

        javax.swing.GroupLayout jPanel_empleadosLayout = new javax.swing.GroupLayout(jPanel_empleados);
        jPanel_empleados.setLayout(jPanel_empleadosLayout);
        jPanel_empleadosLayout.setHorizontalGroup(
            jPanel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_empleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel_empleadosLayout.setVerticalGroup(
            jPanel_empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_empleadosLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        jPanel3.add(jPanel_empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 90, 30));

        jPanel_balances.setBackground(new java.awt.Color(0, 102, 102));
        jPanel_balances.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_balancesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_balancesMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Balances");

        javax.swing.GroupLayout jPanel_balancesLayout = new javax.swing.GroupLayout(jPanel_balances);
        jPanel_balances.setLayout(jPanel_balancesLayout);
        jPanel_balancesLayout.setHorizontalGroup(
            jPanel_balancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_balancesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel_balancesLayout.setVerticalGroup(
            jPanel_balancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_balancesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel_balances, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 90, 30));

        jPanel_eventos.setBackground(new java.awt.Color(0, 102, 102));
        jPanel_eventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel_eventosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel_eventosMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Eventos");

        javax.swing.GroupLayout jPanel_eventosLayout = new javax.swing.GroupLayout(jPanel_eventos);
        jPanel_eventos.setLayout(jPanel_eventosLayout);
        jPanel_eventosLayout.setHorizontalGroup(
            jPanel_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_eventosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel_eventosLayout.setVerticalGroup(
            jPanel_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_eventosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel_eventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 90, 450));

        jTabbedPane2.setBackground(new java.awt.Color(0, 102, 102));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane2KeyPressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reservas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_reservasAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Fecha", "Cliente", "Mesa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_reservasAdmin);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 640, 250));
        jPanel4.add(jTextField_administrador_reserva_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, 20));

        jLabel27.setText("Id:");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel28.setText("Fecha:");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));
        jPanel4.add(jTextField_administrador_reserva_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 60, 20));

        jLabel29.setText("Cliente:");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));
        jPanel4.add(jTextField_administrador_reserva_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 90, -1));

        jLabel30.setText("Mesa:");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jButton_administrador_reservas_agregar.setText("Ver");
        jButton_administrador_reservas_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_administrador_reservas_agregarActionPerformed(evt);
            }
        });
        jPanel4.add(jButton_administrador_reservas_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel4.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jTabbedPane2.addTab("Reservas", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));
        jPanel9.setForeground(new java.awt.Color(0, 0, 0));

        jTable_clientesAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Telefono", "Correo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable_clientesAdmin);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 250));

        jButton1.setText("Ver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        jTabbedPane2.addTab("Clientes", jPanel5);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mesas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));

        jTable_mesasAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Ubicacion", "Capacidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_mesasAdmin);

        jLabel20.setText("Ubicacion:");

        jComboBox_administrador_mesas_ubi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interior", "Exterior" }));

        btn_administrador_mesa_modificar.setText("Modificar");

        btn_administrador_mesa_eliminar.setText("Eliminar");
        btn_administrador_mesa_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_administrador_mesa_eliminarActionPerformed(evt);
            }
        });

        jLabel22.setText("Cliente:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_administrador_mesas_ubi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_administrador_mesa_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_administrador_mesa_modificar))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_administrador_mesa_eliminar)
                                .addGap(2, 2, 2)))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jComboBox_administrador_mesas_ubi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jTextField_administrador_mesa_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_administrador_mesa_modificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_administrador_mesa_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 250));

        jLabel19.setText("Numero");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jTabbedPane2.addTab("Mesas", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empleados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jButton_administrador_empleado_agregar.setText("Agregar");
        jButton_administrador_empleado_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_administrador_empleado_agregarActionPerformed(evt);
            }
        });

        jLabel23.setText("Contraseña: ");

        jTable_empleadosAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Correo", "Rol"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable_empleadosAdmin);

        jLabel24.setText("Correo:");

        jLabel25.setText("Rol:");

        jComboBox_administrador_empleado_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Mesero", "Recepcionista" }));
        jComboBox_administrador_empleado_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_administrador_empleado_rolActionPerformed(evt);
            }
        });

        jTextField_administrador_empleado_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_administrador_empleado_nombreActionPerformed(evt);
            }
        });

        jLabel26.setText("Nombre:");

        jButtonVerEmpleados.setText("Ver");
        jButtonVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jButtonVerEmpleados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_administrador_empleado_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_administrador_empleado_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_administrador_empleado_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_administrador_empleado_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_administrador_empleado_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(191, 191, 191)))))
                .addGap(16, 16, 16))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField_administrador_empleado_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jComboBox_administrador_empleado_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel23)
                    .addComponent(jButton_administrador_empleado_agregar)
                    .addComponent(jTextField_administrador_empleado_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_administrador_empleado_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButtonVerEmpleados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        jTabbedPane2.addTab("Empleados", jPanel7);

        jPanel8.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Balances", jPanel8);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_eventosEspeciales.setBackground(new java.awt.Color(0, 102, 102));
        jPanel_eventosEspeciales.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bloqueo / Eventos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel13.setText("Fecha:");

        jTextField_fechaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fechaEventoActionPerformed(evt);
            }
        });

        jButton_bloqueoMesas.setText("Bloquear");
        jButton_bloqueoMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bloqueoMesasActionPerformed(evt);
            }
        });

        jTable_bloqueoMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mesa", "Fecha", "Hora Inicio", "Hora Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable_bloqueoMesas);

        jLabel4.setText("Hora Inicio");

        jComboBoxHoraInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "18", "20", "22", "00" }));

        jLabel5.setText("Hora Fin");

        jComboBoxHoraFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "18", "20", "22" }));

        jLabel6.setText("Mesa");

        jComboBoxMesas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jButtonVerBloqueMesaEvento.setText("Ver");
        jButtonVerBloqueMesaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerBloqueMesaEventoActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_eventosEspecialesLayout = new javax.swing.GroupLayout(jPanel_eventosEspeciales);
        jPanel_eventosEspeciales.setLayout(jPanel_eventosEspecialesLayout);
        jPanel_eventosEspecialesLayout.setHorizontalGroup(
            jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
            .addGroup(jPanel_eventosEspecialesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_eventosEspecialesLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_eventosEspecialesLayout.createSequentialGroup()
                        .addGroup(jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_eventosEspecialesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(35, 35, 35)
                                .addComponent(jButtonVerBloqueMesaEvento)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel_eventosEspecialesLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_fechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_bloqueoMesas)))
                        .addGap(32, 32, 32))))
        );
        jPanel_eventosEspecialesLayout.setVerticalGroup(
            jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_eventosEspecialesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_fechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_bloqueoMesas)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel_eventosEspecialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerBloqueMesaEvento)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField_fechaEvento.getAccessibleContext().setAccessibleName("");

        jPanel12.add(jPanel_eventosEspeciales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 390));
        jPanel_eventosEspeciales.getAccessibleContext().setAccessibleName("Bloqueo eventos");

        jTabbedPane2.addTab("Bloqueo / Eventos", jPanel12);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 810, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarTablaBloqueoMesaEvento(){
          
        bmes = empleadoDAO.obtenerBloqueosMesasEventosEspeciales();
        
        DefaultTableModel model = (DefaultTableModel) jTable_bloqueoMesas.getModel();
        model.setRowCount(0); //Elimina las filas existentes;

        
        for(BloqueoMesaEventoEspecial b: bmes){
            String horaInicio;
            if(b.getHoraInicio()== null){
                horaInicio = "";
            }else{
                horaInicio = b.getHoraInicio().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
            }
            String horaFin;
            if(b.getHoraFin()== null){
                horaFin = "";
            }else{
                horaFin = b.getHoraFin().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
            }
            model.addRow(new Object[]{
                b.getNumMesa()== 0? "Todas":b.getNumMesa(),
                b.getFecha().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")),
                horaInicio,
                horaFin
            });
            }
        
            
        
    }
    
    private void jButton_Administrador_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Administrador_salirActionPerformed
        dispose();
        Inicio login = new Inicio();
        login.setVisible(true);
    }//GEN-LAST:event_jButton_Administrador_salirActionPerformed

    private void actualizarTablaMesas(){
        
        ArrayList<Cliente> clientes = clienteDAO.obtenerClientes();

        DefaultTableModel model = (DefaultTableModel) this.jTable_clientesAdmin.getModel();
        model.setRowCount(0); // Limpia todas las filas existentes        
        
        for (Cliente c : clientes) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNombre(),
                c.getTelefono(),
                c.getCorreo()
            });
        }
        
    }
    private void actualizarTablaCliente(){
        
        
        ArrayList<Cliente> clientes = clienteDAO.obtenerClientes();

        DefaultTableModel model = (DefaultTableModel) this.jTable_clientesAdmin.getModel();
        model.setRowCount(0); // Limpia todas las filas existentes        
        
        for (Cliente c : clientes) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNombre(),
                c.getTelefono(),
                c.getCorreo()
            });
        }
        
    }
    private void actualizarTablaEmpleado(){
        
        ArrayList<Empleado> empleados = empleadoDAO.obtenerEmpleados();

        DefaultTableModel model = (DefaultTableModel) this.jTable_empleadosAdmin.getModel();
        model.setRowCount(0); // Limpia todas las filas existentes        
        
        for (Empleado e : empleados) {
            model.addRow(new Object[]{
                e.getId(),
                e.getNombre(),
                e.getCorreo(),
                e.getRol().toString()
            });
        }
        
        
    }
    private void txt_reservasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_reservasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_reservasMouseEntered

    private void jPanel_reservasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_reservasMouseExited
        jPanel_reservas.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jPanel_reservasMouseExited

    private void jPanel_reservasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_reservasMouseEntered
        jPanel_reservas.setBackground(new Color(0, 152, 152));
    }//GEN-LAST:event_jPanel_reservasMouseEntered

    private void jPanel_clientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_clientesMouseEntered
        jPanel_clientes.setBackground(new Color(0, 152, 152));
    }//GEN-LAST:event_jPanel_clientesMouseEntered

    private void jPanel_clientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_clientesMouseExited
        jPanel_clientes.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jPanel_clientesMouseExited

    private void jPanel_mesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_mesasMouseEntered
          jPanel_mesas.setBackground(new Color(0, 152, 152));
    }//GEN-LAST:event_jPanel_mesasMouseEntered

    private void jPanel_mesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_mesasMouseExited
        jPanel_mesas.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jPanel_mesasMouseExited

    private void jPanel_empleadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_empleadosMouseEntered
         jPanel_empleados.setBackground(new Color(0, 152, 152));
    }//GEN-LAST:event_jPanel_empleadosMouseEntered

    private void jPanel_empleadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_empleadosMouseExited
         jPanel_empleados.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jPanel_empleadosMouseExited

    private void jPanel_balancesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_balancesMouseEntered
       jPanel_balances.setBackground(new Color(0, 152, 152));
    }//GEN-LAST:event_jPanel_balancesMouseEntered

    private void jPanel_balancesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_balancesMouseExited
       jPanel_balances.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jPanel_balancesMouseExited

    private void jPanel_eventosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_eventosMouseEntered
          jPanel_eventos.setBackground(new Color(0, 152, 152));
    }//GEN-LAST:event_jPanel_eventosMouseEntered

    private void jPanel_eventosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel_eventosMouseExited
         jPanel_eventos.setBackground(new Color(0, 102, 102));
    }//GEN-LAST:event_jPanel_eventosMouseExited

    private void jTabbedPane2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2KeyPressed

    private void jButton_bloqueoMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bloqueoMesasActionPerformed
        BloqueoMesaEventoEspecial b = new BloqueoMesaEventoEspecial();
        String auxFecha = jTextField_fechaEvento.getText();
                
        LocalDate fechaBloqueoEvento;
        if(ClienteController.esFormatoFechaValido(auxFecha)){
            try{
            fechaBloqueoEvento = LocalDate.parse(auxFecha, DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            }catch(java.time.format.DateTimeParseException e){
                javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una fecha válida", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese una fecha en formato dd/mm/aaaa", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        b.setFecha(fechaBloqueoEvento);
        
        String auxNumMesa = jComboBoxMesas.getSelectedItem().toString();
        
        String auxHoraInicio = jComboBoxHoraInicio.getSelectedItem().toString();
        String auxHoraFin = jComboBoxHoraFin.getSelectedItem().toString();
        
        
        
        int numeroMesa;
        LocalTime horaInicio;
        LocalTime horaFin;
        if(auxNumMesa.equals("Todas")){
            if(Integer.parseInt(auxHoraInicio) > Integer.parseInt(auxHoraFin)){
                javax.swing.JOptionPane.showMessageDialog(this, "La hora de inicio del evento debe ser menor a la hora de su finalización", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            numeroMesa = 0;
            horaInicio = LocalTime.parse(auxHoraInicio + ":00:00", 
                    DateTimeFormatter.ofPattern("HH:mm:ss"));
            horaFin = LocalTime.parse(auxHoraFin + ":00:00", 
                    DateTimeFormatter.ofPattern("HH:mm:ss"));
            
            b.setNumMesa(numeroMesa);
            b.setHoraInicio(horaInicio);
            b.setHoraFin(horaFin);
            
            if (empleadoDAO.bloquearMesaEventoEspecial(b)){
                javax.swing.JOptionPane.showMessageDialog(this, "Se añadió el evento.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al añadir el evento", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }else{
            numeroMesa = Integer.parseInt(auxNumMesa);
            b.setNumMesa(numeroMesa);
            if (empleadoDAO.bloquearMesaEventoEspecial(b)){
                javax.swing.JOptionPane.showMessageDialog(this, "Se añadió el bloqueo de mesa.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al añadir el bloqueo de mesa", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        }
        actualizarTablaBloqueoMesaEvento();
    }//GEN-LAST:event_jButton_bloqueoMesasActionPerformed

    private void jTextField_fechaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fechaEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fechaEventoActionPerformed

    private void jTextField_administrador_empleado_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_administrador_empleado_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_administrador_empleado_nombreActionPerformed

    private void btn_administrador_mesa_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_administrador_mesa_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_administrador_mesa_eliminarActionPerformed

    private void jButton_administrador_reservas_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_administrador_reservas_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_administrador_reservas_agregarActionPerformed

    private void jButtonVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerEmpleadosActionPerformed
       actualizarTablaEmpleado();
    }//GEN-LAST:event_jButtonVerEmpleadosActionPerformed

    private void jButton_administrador_empleado_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_administrador_empleado_agregarActionPerformed
        String nombre = this.jTextField_administrador_empleado_nombre.getText();
        String correo = this.jTextField_administrador_empleado_correo.getText();
        String contrasenia = String.valueOf(this.jTextField_administrador_empleado_contrasenia.getPassword());
        Rol rol = null;
        switch(this.jComboBox_administrador_empleado_rol.getSelectedItem().toString()){
            case "Administrador":
                rol = Rol.Administrador;
                break;
            case "Mesero":
                rol = Rol.Mesero;
                break;
            case "Recepcionista": 
                rol = Rol.Recepcionista;
                break;
            case "Cocinero":
                rol = Rol.Cocinero;
                break;
            default:
                break;
        }
        if(nombre.equals("")
                || correo.equals("")
                || contrasenia.equals("")){
            javax.swing.JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
            }else{
            if(ClienteController.esCorreoElectronicoValido(correo)){
                Empleado emp = new Empleado();
                emp.setNombre(nombre);
                emp.setCorreo(correo);
                emp.setContrasenia(contrasenia);
                emp.setRol(rol);
                System.out.println(emp);
                if(empleadoDAO.registrarEmpleado(emp)){
                    javax.swing.JOptionPane.showMessageDialog(null,"Registrado exitosamente");
                    actualizarTablaEmpleado();
                }
            } else{
                javax.swing.JOptionPane.showMessageDialog(null,"Ingrese un correo electronico valido");
            }

        }
    }//GEN-LAST:event_jButton_administrador_empleado_agregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        actualizarTablaCliente();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox_administrador_empleado_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_administrador_empleado_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_administrador_empleado_rolActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonVerBloqueMesaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerBloqueMesaEventoActionPerformed
        actualizarTablaBloqueoMesaEvento();
    }//GEN-LAST:event_jButtonVerBloqueMesaEventoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        bme = bmes.get(jTable_bloqueoMesas.getSelectedRow());
        
        if(empleadoDAO.eliminarBloqueoEvento(bme)){
                javax.swing.JOptionPane.showMessageDialog(this, "Bloqueo o evento eliminado con éxito.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                this.actualizarTablaBloqueoMesaEvento();
            }else{
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar bloqueo o evento", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            }

    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_administrador_mesa_eliminar;
    public javax.swing.JButton btn_administrador_mesa_modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonVerBloqueMesaEvento;
    private javax.swing.JButton jButtonVerEmpleados;
    public javax.swing.JButton jButton_Administrador_salir;
    public javax.swing.JButton jButton_administrador_empleado_agregar;
    public javax.swing.JButton jButton_administrador_reservas_agregar;
    private javax.swing.JButton jButton_bloqueoMesas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxHoraFin;
    private javax.swing.JComboBox<String> jComboBoxHoraInicio;
    private javax.swing.JComboBox<String> jComboBoxMesas;
    public javax.swing.JComboBox<String> jComboBox_administrador_empleado_rol;
    public javax.swing.JComboBox<String> jComboBox_administrador_mesas_ubi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_balances;
    private javax.swing.JPanel jPanel_clientes;
    private javax.swing.JPanel jPanel_empleados;
    private javax.swing.JPanel jPanel_eventos;
    private javax.swing.JPanel jPanel_eventosEspeciales;
    private javax.swing.JPanel jPanel_mesas;
    private javax.swing.JPanel jPanel_reservas;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTabbedPane jTabbedPane2;
    public javax.swing.JTable jTable_bloqueoMesas;
    public javax.swing.JTable jTable_clientesAdmin;
    public javax.swing.JTable jTable_empleadosAdmin;
    public javax.swing.JTable jTable_mesasAdmin;
    private javax.swing.JPasswordField jTextField_administrador_empleado_contrasenia;
    public javax.swing.JTextField jTextField_administrador_empleado_correo;
    public javax.swing.JTextField jTextField_administrador_empleado_nombre;
    public javax.swing.JTextField jTextField_administrador_mesa_cliente;
    public javax.swing.JTextField jTextField_administrador_reserva_cliente;
    public javax.swing.JTextField jTextField_administrador_reserva_fecha;
    public javax.swing.JTextField jTextField_administrador_reserva_id;
    public javax.swing.JTextField jTextField_fechaEvento;
    public javax.swing.JTable tabla_reservasAdmin;
    private javax.swing.JLabel txt_reservas;
    // End of variables declaration//GEN-END:variables
}
